// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlotSelector {
    #[prost(uint32, optional, tag = "1")]
    pub id: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlotConfigSpecification {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub config: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlotConfigResults {
    #[prost(message, repeated, tag = "1")]
    pub data: ::prost::alloc::vec::Vec<PlotConfigSpecification>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlotConfig {
    #[prost(string, tag = "1")]
    pub config: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlotConfigResult {
    #[prost(oneof = "plot_config_result::Result", tags = "1, 2, 3")]
    pub result: ::core::option::Option<plot_config_result::Result>,
}
/// Nested message and enum types in `PlotConfigResult`.
pub mod plot_config_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Config(super::PlotConfigResults),
        #[prost(message, tag = "2")]
        UserConfig(super::PlotConfig),
        #[prost(string, tag = "3")]
        ErrMsg(::prost::alloc::string::String),
    }
}
/// Holds an array of device names (strings).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceList {
    #[prost(string, repeated, tag = "1")]
    pub device: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Property {
    #[prost(string, optional, tag = "1")]
    pub primary_units: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub common_units: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(double, tag = "3")]
    pub min_val: f64,
    #[prost(double, tag = "4")]
    pub max_val: f64,
    #[prost(uint32, tag = "5")]
    pub p_index: u32,
    #[prost(uint32, tag = "6")]
    pub c_index: u32,
    #[prost(double, repeated, tag = "7")]
    pub coeff: ::prost::alloc::vec::Vec<f64>,
    #[prost(bool, tag = "8")]
    pub is_step_motor: bool,
    #[prost(bool, tag = "9")]
    pub is_destructive_read: bool,
    #[prost(bool, tag = "10")]
    pub is_fe_scaling: bool,
    #[prost(bool, tag = "11")]
    pub is_contr_setting: bool,
    #[prost(bool, tag = "12")]
    pub is_knobbable: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DigitalStatusItem {
    #[prost(uint32, tag = "1")]
    pub mask_val: u32,
    #[prost(uint32, tag = "2")]
    pub match_val: u32,
    #[prost(bool, tag = "3")]
    pub invert: bool,
    #[prost(string, tag = "4")]
    pub short_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub long_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub true_str: ::prost::alloc::string::String,
    #[prost(uint32, tag = "7")]
    pub true_color: u32,
    #[prost(string, tag = "8")]
    pub true_char: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub false_str: ::prost::alloc::string::String,
    #[prost(uint32, tag = "10")]
    pub false_color: u32,
    #[prost(string, tag = "11")]
    pub false_char: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DigitalExtStatusItem {
    #[prost(uint32, tag = "1")]
    pub bit_no: u32,
    #[prost(uint32, tag = "2")]
    pub color0: u32,
    #[prost(string, tag = "3")]
    pub name0: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub color1: u32,
    #[prost(string, tag = "5")]
    pub name1: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DigitalStatus {
    #[prost(message, repeated, tag = "1")]
    pub bits: ::prost::alloc::vec::Vec<DigitalStatusItem>,
    #[prost(message, repeated, tag = "2")]
    pub ext_bits: ::prost::alloc::vec::Vec<DigitalExtStatusItem>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DigitalControlItem {
    #[prost(uint32, tag = "1")]
    pub value: u32,
    #[prost(string, tag = "2")]
    pub short_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub long_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DigitalControl {
    #[prost(message, repeated, tag = "1")]
    pub cmds: ::prost::alloc::vec::Vec<DigitalControlItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceInfo {
    #[prost(uint32, tag = "1")]
    pub device_index: u32,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub reading: ::core::option::Option<Property>,
    #[prost(message, optional, tag = "4")]
    pub setting: ::core::option::Option<Property>,
    #[prost(message, optional, tag = "5")]
    pub control: ::core::option::Option<DigitalControl>,
    #[prost(message, optional, tag = "6")]
    pub status: ::core::option::Option<DigitalStatus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InfoEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(oneof = "info_entry::Result", tags = "2, 3")]
    pub result: ::core::option::Option<info_entry::Result>,
}
/// Nested message and enum types in `InfoEntry`.
pub mod info_entry {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "2")]
        Device(super::DeviceInfo),
        #[prost(string, tag = "3")]
        ErrMsg(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceInfoReply {
    #[prost(message, repeated, tag = "1")]
    pub set: ::prost::alloc::vec::Vec<InfoEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AlarmBlock {
    /// Device Identifier (4 byte integer)
    #[prost(uint32, tag = "1")]
    pub di: u32,
    /// Property type (1 byte integer)
    #[prost(uint32, tag = "2")]
    pub pi: u32,
    /// Status word (2 byte binary, hexified)
    #[prost(int32, tag = "3")]
    pub status: i32,
    /// Min/Nominal value (4 byte integer)
    #[prost(int32, tag = "4")]
    pub min_or_nom: i32,
    /// Max/Tolerance/Mask (4 byte integer)
    #[prost(int32, tag = "5")]
    pub max_or_tol: i32,
    /// Number of out-of-tolerance samples (1 byte integer)
    #[prost(uint32, tag = "6")]
    pub tries_needed: u32,
    /// Current tries from front end (1 byte integer)
    #[prost(uint32, tag = "7")]
    pub tries_now: u32,
    /// Clock event number (1 byte binary)
    #[prost(uint32, tag = "8")]
    pub clock_event_no: u32,
    /// Subfunction code (1 byte integer)
    #[prost(uint32, tag = "9")]
    pub subfunction_code: u32,
    /// Front-end specific data (6 byte binary, hexified)
    #[prost(string, tag = "10")]
    pub specific_data: ::prost::alloc::string::String,
    /// Alarm block number (4 byte integer)
    #[prost(uint32, tag = "11")]
    pub segment: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceDigitalAlarm {
    #[prost(uint32, tag = "1")]
    pub di: u32,
    #[prost(int32, tag = "2")]
    pub condition: i32,
    #[prost(int32, tag = "3")]
    pub mask: i32,
    #[prost(uint32, tag = "4")]
    pub alarm_text_id: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceAnalogAlarm {
    #[prost(uint32, tag = "1")]
    pub di: u32,
    #[prost(uint32, tag = "2")]
    pub alarm_text_id: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AlarmTextIdList {
    #[prost(uint32, repeated, tag = "1")]
    pub alarm_text_id: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceAlarmText {
    /// (1-99999)
    #[prost(uint32, tag = "1")]
    pub alarm_text_id: u32,
    #[prost(uint32, tag = "2")]
    pub length: u32,
    /// (0-10, 10 represents the highest priority)
    #[prost(uint32, tag = "3")]
    pub priority: u32,
    #[prost(uint32, tag = "4")]
    pub hand_code: u32,
    #[prost(uint32, tag = "5")]
    pub sound_id: u32,
    #[prost(uint32, tag = "6")]
    pub speech_id: u32,
    #[prost(uint32, tag = "7")]
    pub spare: u32,
    /// 80 byte alphanumeric (not null nor blanks)
    #[prost(string, tag = "8")]
    pub text: ::prost::alloc::string::String,
    /// 128 byte alphanumeric (may be blank if no URL)
    #[prost(string, tag = "9")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceAlarmTextList {
    #[prost(message, repeated, tag = "1")]
    pub device_alarm_text: ::prost::alloc::vec::Vec<DeviceAlarmText>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AlarmInfo {
    #[prost(string, tag = "1")]
    pub device_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub alarm_block: ::core::option::Option<AlarmBlock>,
    #[prost(message, optional, tag = "3")]
    pub device_analog_alarm: ::core::option::Option<DeviceAnalogAlarm>,
    #[prost(message, optional, tag = "4")]
    pub device_digital_alarm: ::core::option::Option<DeviceDigitalAlarm>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AlarmInfoReply {
    #[prost(message, repeated, tag = "1")]
    pub alarm_info: ::prost::alloc::vec::Vec<AlarmInfo>,
}
/// Generated client implementations.
pub mod dev_db_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct DevDbClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl DevDbClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> DevDbClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> DevDbClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            DevDbClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_device_info(
            &mut self,
            request: impl tonic::IntoRequest<super::DeviceList>,
        ) -> std::result::Result<
            tonic::Response<super::DeviceInfoReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/services.devdb.DevDB/getDeviceInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("services.devdb.DevDB", "getDeviceInfo"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_all_alarm_info(
            &mut self,
            request: impl tonic::IntoRequest<super::DeviceList>,
        ) -> std::result::Result<tonic::Response<super::AlarmInfoReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/services.devdb.DevDB/getAllAlarmInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("services.devdb.DevDB", "getAllAlarmInfo"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_alarm_text(
            &mut self,
            request: impl tonic::IntoRequest<super::AlarmTextIdList>,
        ) -> std::result::Result<
            tonic::Response<super::DeviceAlarmTextList>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/services.devdb.DevDB/getAlarmText",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("services.devdb.DevDB", "getAlarmText"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_plot_configuration(
            &mut self,
            request: impl tonic::IntoRequest<super::PlotSelector>,
        ) -> std::result::Result<
            tonic::Response<super::PlotConfigResult>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/services.devdb.DevDB/getPlotConfiguration",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("services.devdb.DevDB", "getPlotConfiguration"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_user_plot_configuration(
            &mut self,
            request: impl tonic::IntoRequest<
                super::super::super::google::protobuf::Empty,
            >,
        ) -> std::result::Result<
            tonic::Response<super::PlotConfigResult>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/services.devdb.DevDB/getUserPlotConfiguration",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("services.devdb.DevDB", "getUserPlotConfiguration"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_plot_configuration(
            &mut self,
            request: impl tonic::IntoRequest<super::PlotSelector>,
        ) -> std::result::Result<
            tonic::Response<super::PlotConfigResult>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/services.devdb.DevDB/deletePlotConfiguration",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("services.devdb.DevDB", "deletePlotConfiguration"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn save_plot_configuration(
            &mut self,
            request: impl tonic::IntoRequest<super::PlotConfigSpecification>,
        ) -> std::result::Result<
            tonic::Response<super::PlotConfigResult>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/services.devdb.DevDB/savePlotConfiguration",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("services.devdb.DevDB", "savePlotConfiguration"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn save_user_plot_configuration(
            &mut self,
            request: impl tonic::IntoRequest<super::PlotConfig>,
        ) -> std::result::Result<
            tonic::Response<super::PlotConfigResult>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/services.devdb.DevDB/saveUserPlotConfiguration",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("services.devdb.DevDB", "saveUserPlotConfiguration"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod dev_db_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with DevDbServer.
    #[async_trait]
    pub trait DevDb: std::marker::Send + std::marker::Sync + 'static {
        async fn get_device_info(
            &self,
            request: tonic::Request<super::DeviceList>,
        ) -> std::result::Result<tonic::Response<super::DeviceInfoReply>, tonic::Status>;
        async fn get_all_alarm_info(
            &self,
            request: tonic::Request<super::DeviceList>,
        ) -> std::result::Result<tonic::Response<super::AlarmInfoReply>, tonic::Status>;
        async fn get_alarm_text(
            &self,
            request: tonic::Request<super::AlarmTextIdList>,
        ) -> std::result::Result<
            tonic::Response<super::DeviceAlarmTextList>,
            tonic::Status,
        >;
        async fn get_plot_configuration(
            &self,
            request: tonic::Request<super::PlotSelector>,
        ) -> std::result::Result<
            tonic::Response<super::PlotConfigResult>,
            tonic::Status,
        >;
        async fn get_user_plot_configuration(
            &self,
            request: tonic::Request<super::super::super::google::protobuf::Empty>,
        ) -> std::result::Result<
            tonic::Response<super::PlotConfigResult>,
            tonic::Status,
        >;
        async fn delete_plot_configuration(
            &self,
            request: tonic::Request<super::PlotSelector>,
        ) -> std::result::Result<
            tonic::Response<super::PlotConfigResult>,
            tonic::Status,
        >;
        async fn save_plot_configuration(
            &self,
            request: tonic::Request<super::PlotConfigSpecification>,
        ) -> std::result::Result<
            tonic::Response<super::PlotConfigResult>,
            tonic::Status,
        >;
        async fn save_user_plot_configuration(
            &self,
            request: tonic::Request<super::PlotConfig>,
        ) -> std::result::Result<
            tonic::Response<super::PlotConfigResult>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct DevDbServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> DevDbServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for DevDbServer<T>
    where
        T: DevDb,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/services.devdb.DevDB/getDeviceInfo" => {
                    #[allow(non_camel_case_types)]
                    struct getDeviceInfoSvc<T: DevDb>(pub Arc<T>);
                    impl<T: DevDb> tonic::server::UnaryService<super::DeviceList>
                    for getDeviceInfoSvc<T> {
                        type Response = super::DeviceInfoReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeviceList>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DevDb>::get_device_info(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = getDeviceInfoSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/services.devdb.DevDB/getAllAlarmInfo" => {
                    #[allow(non_camel_case_types)]
                    struct getAllAlarmInfoSvc<T: DevDb>(pub Arc<T>);
                    impl<T: DevDb> tonic::server::UnaryService<super::DeviceList>
                    for getAllAlarmInfoSvc<T> {
                        type Response = super::AlarmInfoReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeviceList>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DevDb>::get_all_alarm_info(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = getAllAlarmInfoSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/services.devdb.DevDB/getAlarmText" => {
                    #[allow(non_camel_case_types)]
                    struct getAlarmTextSvc<T: DevDb>(pub Arc<T>);
                    impl<T: DevDb> tonic::server::UnaryService<super::AlarmTextIdList>
                    for getAlarmTextSvc<T> {
                        type Response = super::DeviceAlarmTextList;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AlarmTextIdList>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DevDb>::get_alarm_text(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = getAlarmTextSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/services.devdb.DevDB/getPlotConfiguration" => {
                    #[allow(non_camel_case_types)]
                    struct getPlotConfigurationSvc<T: DevDb>(pub Arc<T>);
                    impl<T: DevDb> tonic::server::UnaryService<super::PlotSelector>
                    for getPlotConfigurationSvc<T> {
                        type Response = super::PlotConfigResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PlotSelector>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DevDb>::get_plot_configuration(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = getPlotConfigurationSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/services.devdb.DevDB/getUserPlotConfiguration" => {
                    #[allow(non_camel_case_types)]
                    struct getUserPlotConfigurationSvc<T: DevDb>(pub Arc<T>);
                    impl<
                        T: DevDb,
                    > tonic::server::UnaryService<
                        super::super::super::google::protobuf::Empty,
                    > for getUserPlotConfigurationSvc<T> {
                        type Response = super::PlotConfigResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::super::super::google::protobuf::Empty,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DevDb>::get_user_plot_configuration(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = getUserPlotConfigurationSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/services.devdb.DevDB/deletePlotConfiguration" => {
                    #[allow(non_camel_case_types)]
                    struct deletePlotConfigurationSvc<T: DevDb>(pub Arc<T>);
                    impl<T: DevDb> tonic::server::UnaryService<super::PlotSelector>
                    for deletePlotConfigurationSvc<T> {
                        type Response = super::PlotConfigResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PlotSelector>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DevDb>::delete_plot_configuration(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = deletePlotConfigurationSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/services.devdb.DevDB/savePlotConfiguration" => {
                    #[allow(non_camel_case_types)]
                    struct savePlotConfigurationSvc<T: DevDb>(pub Arc<T>);
                    impl<
                        T: DevDb,
                    > tonic::server::UnaryService<super::PlotConfigSpecification>
                    for savePlotConfigurationSvc<T> {
                        type Response = super::PlotConfigResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PlotConfigSpecification>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DevDb>::save_plot_configuration(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = savePlotConfigurationSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/services.devdb.DevDB/saveUserPlotConfiguration" => {
                    #[allow(non_camel_case_types)]
                    struct saveUserPlotConfigurationSvc<T: DevDb>(pub Arc<T>);
                    impl<T: DevDb> tonic::server::UnaryService<super::PlotConfig>
                    for saveUserPlotConfigurationSvc<T> {
                        type Response = super::PlotConfigResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PlotConfig>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DevDb>::save_user_plot_configuration(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = saveUserPlotConfigurationSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for DevDbServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "services.devdb.DevDB";
    impl<T> tonic::server::NamedService for DevDbServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
