// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Value {
    #[prost(oneof = "value::Value", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12")]
    pub value: ::core::option::Option<value::Value>,
}
/// Nested message and enum types in `Value`.
pub mod value {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ScalarArray {
        #[prost(double, repeated, tag = "1")]
        pub value: ::prost::alloc::vec::Vec<f64>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct TextArray {
        #[prost(string, repeated, tag = "1")]
        pub value: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Int64Array {
        #[prost(int64, repeated, tag = "1")]
        pub value: ::prost::alloc::vec::Vec<i64>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Uint64Array {
        #[prost(uint64, repeated, tag = "1")]
        pub value: ::prost::alloc::vec::Vec<u64>,
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct AnalogAlarm {
        #[prost(double, tag = "1")]
        pub minimum: f64,
        #[prost(double, tag = "2")]
        pub maximum: f64,
        #[prost(bool, tag = "3")]
        pub alarm_enable: bool,
        #[prost(bool, tag = "4")]
        pub alarm_status: bool,
        #[prost(bool, tag = "5")]
        pub abort: bool,
        #[prost(bool, tag = "6")]
        pub abort_inhibit: bool,
        #[prost(uint32, tag = "7")]
        pub tries_needed: u32,
        #[prost(uint32, tag = "8")]
        pub tries_now: u32,
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct DigitalAlarm {
        #[prost(int32, tag = "1")]
        pub nominal: i32,
        #[prost(uint32, tag = "2")]
        pub mask: u32,
        #[prost(bool, tag = "3")]
        pub alarm_enable: bool,
        #[prost(bool, tag = "4")]
        pub alarm_status: bool,
        #[prost(bool, tag = "5")]
        pub abort: bool,
        #[prost(bool, tag = "6")]
        pub abort_inhibit: bool,
        #[prost(uint32, tag = "7")]
        pub tries_needed: u32,
        #[prost(uint32, tag = "8")]
        pub tries_now: u32,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct BasicStatus {
        #[prost(map = "string, string", tag = "1")]
        pub value: ::std::collections::HashMap<
            ::prost::alloc::string::String,
            ::prost::alloc::string::String,
        >,
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(double, tag = "1")]
        Scalar(f64),
        #[prost(message, tag = "2")]
        ScalarArr(ScalarArray),
        #[prost(bytes, tag = "3")]
        Raw(::prost::alloc::vec::Vec<u8>),
        #[prost(string, tag = "4")]
        Text(::prost::alloc::string::String),
        #[prost(message, tag = "5")]
        TextArr(TextArray),
        #[prost(message, tag = "6")]
        AnaAlarm(AnalogAlarm),
        #[prost(message, tag = "7")]
        DigAlarm(DigitalAlarm),
        #[prost(message, tag = "8")]
        BasicStatus(BasicStatus),
        #[prost(int64, tag = "9")]
        Int(i64),
        #[prost(uint64, tag = "10")]
        Uint(u64),
        #[prost(message, tag = "11")]
        IntArr(Int64Array),
        #[prost(message, tag = "12")]
        UintArr(Uint64Array),
    }
}
