//! Root of the `rust-grpc-lib` crate.
//!
//! Declares the public module tree and re-exports the proc-macro entry points
//! from `grpc-macro` so consumers never need a direct dependency on that crate.
//!
//! # Modules
//!
//! | Module | Feature gate | Purpose |
//! |---|---|---|
//! | [`auth`] | `auth` (default) | JWT interceptors, validation layer, token sources |
//! | [`build_support`] | `build` | Proto code-generation helpers for `build.rs` |
//! | [`pool`] | always | Process-wide lazily-connected channel pool |
//!
//! # Re-exported macros
//!
//! | Item | Feature gate | What it generates |
//! |---|---|---|
//! | [`GrpcClient`] | `auth` (default) | `from_endpoint_with_provider` on tonic client structs |
//! | [`GrpcNoAuthClient`] | `unauthenticated` | `from_endpoint` (no-auth) on tonic client structs |
//! | [`grpc_service`] | `auth` (default) | Role-checking guards on `impl Trait for Type` blocks |
//!
//! See each module and the `grpc-macro` crate for full documentation.

/// JWT interceptors, validation layer, and re-exports from `rust-auth-lib`.
///
/// Enabled by the `auth` feature (on by default). See [`auth`] for the full
/// list of re-exported types and the two sub-modules it contains:
/// [`auth::interceptor`] and [`auth::layer`].
#[cfg(any(feature = "auth", doc, test))]
pub mod auth;

/// Build-time helpers for compiling the bundled `.proto` definitions into Rust.
///
/// Enabled by the `build` feature (off by default). The sole public entry
/// point is [`build_support::generate_protos`], called from a consumer's
/// `build.rs`.
#[cfg(any(feature = "build", doc, test))]
pub mod build_support;

/// Process-wide gRPC channel pool.
///
/// The sole public function is [`pool::get_channel`]. Consumers do not
/// typically call it directly — the constructors generated by [`GrpcClient`]
/// and [`GrpcNoAuthClient`] call it internally.
pub mod pool;

/// Derive macro that generates `from_endpoint_with_provider` on a tonic client
/// struct, wiring it into [`pool::get_channel`] with JWT auth.
///
/// Applied automatically by [`build_support::Config::new`] to every generated
/// client. Re-exported here so consumers can also apply it to custom wrapper
/// types without a direct dependency on `grpc-macro`.
#[cfg(any(feature = "auth", doc, test))]
pub use grpc_macro::GrpcClient;

/// Derive macro that generates `from_endpoint` (no-auth) on a tonic client
/// struct. Intended for test harnesses only; requires the `unauthenticated`
/// feature.
#[cfg(any(feature = "unauthenticated", doc, test))]
pub use grpc_macro::GrpcNoAuthClient;

/// Attribute macro applied to `impl Trait for Type` blocks that injects
/// Keycloak role-checking guards into methods annotated with `#[roles(...)]`.
///
/// Re-exported here so consumers can write `#[rust_grpc_lib::grpc_service]`
/// without a direct dependency on `grpc-macro`.
#[cfg(any(feature = "auth", doc, test))]
pub use grpc_macro::grpc_service;
