//! gRPC connection pool and code-generation helpers for Controls group services.
//!
//! This library provides:
//!
//! - **Code-generation helpers** — [`build_support::generate_protos`] (behind
//!   the `build` feature) drives `tonic`/`prost` compilation of the bundled
//!   `.proto` files and writes a `proto.rs` into your crate's `OUT_DIR`.
//! - **Connection pooling** — a process-wide pool of lazily-connected channels
//!   via [`pool::get`], so all callers share connections without coordinating
//!   themselves.
//! - **[`GrpcClient`] trait and derive macro** — a thin trait that all generated
//!   tonic clients implement, enabling [`pool::get`] to construct any client type
//!   from a shared channel. The `#[derive(GrpcClient)]` macro is re-exported here
//!   for the rare case where you need to implement the trait on a custom wrapper.
//!
//! # Code generation is the consumer's responsibility
//!
//! This library does **not** expose a `proto` module of its own. Instead, you
//! call [`build_support::generate_protos`] from your own `build.rs`, then
//! include the output in your crate:
//!
//! ```rust,ignore
//! // build.rs
//! use rust_grpc_lib::build_support::{ Config, generate_protos };
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let config = Config::new();
//!     // < optional calls to configure custom attributes here >
//!     generate_protos(config)?;
//!     Ok(())
//! }
//! ```
//!
//! ```rust,ignore
//! // src/proto.rs  (or inline in src/lib.rs)
//! include!(concat!(env!("OUT_DIR"), "/proto.rs"));
//! ```
//!
//! # Runtime requirement
//!
//! This library requires a [Tokio](https://tokio.rs) runtime. Tonic's transport
//! layer is built on Tokio; there is no way to use it without one.
//!
//! # Quick start
//!
//! After setting up code generation (see above), call [`pool::get`] with the
//! desired client type and endpoint:
//!
//! ```rust,ignore
//! // `proto` is the module you set up with include!(concat!(env!("OUT_DIR"), "/proto.rs"))
//! use crate::proto::services::alarm_commands::alarm_commands_client::AlarmCommandsClient;
//!
//! // Inside #[tokio::main] or any async context:
//! let client: AlarmCommandsClient<_> = rust_grpc_lib::pool::get("http://alarm-commands-host:50051")?;
//! ```
//!
//! # Connection pooling
//!
//! Channels are keyed by the endpoint string. Calling [`pool::get`] multiple
//! times with the same endpoint returns clients that share the same underlying
//! channel. Connections are established lazily on the first RPC, not at the
//! time [`pool::get`] is called.
//!
//! # Adding derive macros to generated types
//!
//! If you need generated structs or enums to implement additional traits (e.g.
//! `serde::Serialize`), make the relevant calls on your [`Config`](crate::build_support::Config) before building:
//!
//! ```rust,ignore
//! // build.rs
//! use rust_grpc_lib::build_support::{ Config, generate_protos };
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let mut config = Config::new();
//!     config = config.type_attribute("some.package", "#[derive(my_macro)]");
//!     config = config.client_attribute("other.package", "#[derive(client_only_macro)]");
//!     generate_protos(config)?;
//!     Ok(())
//! }
//! ```
//!
//! # Keepalive configuration
//!
//! HTTP/2 keepalive probes are sent on every channel. The timing can be
//! overridden at runtime via environment variables:
//!
//! | Variable | Default | Meaning |
//! |---|---|---|
//! | `RUST_GRPC_LIB_KEEP_ALIVE_INTERVAL_SECS` | `30` | Seconds between keepalive pings |
//! | `RUST_GRPC_LIB_KEEP_ALIVE_TIMEOUT_SECS` | `10` | Seconds to wait for a keepalive ping acknowledgement before closing the connection |
//!
//! Keepalive pings are also sent while the connection is idle.

use tonic::transport::Channel;

/// Re-export of the [`GrpcClient`] derive macro so consumers can use
/// `#[derive(rust_grpc_lib::GrpcClient)]` without adding a separate
/// dependency on the proc-macro crate.
pub use grpc_client_macro::GrpcClient;

#[cfg(any(feature = "build", doc, test))]
pub mod build_support;

pub mod pool;

/// Marker trait for gRPC client types that can be constructed from a [`Channel`].
///
/// All generated tonic service clients implement this trait automatically via
/// the bundled `#[derive(GrpcClient)]` macro — you do not need to implement it
/// yourself unless you are wrapping a generated client in your own newtype.
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not implement `GrpcClient`",
    label = "`{Self}` is not a generated service client from this library",
    note = "Client types generated by rust-grpc-lib implement GrpcClient by default. \
        Manually implement it for your client if it is not from rust-grpc-lib."
)]
pub trait GrpcClient: Sized {
    /// Construct a client from an existing [`Channel`].
    fn from_channel(channel: Channel) -> Self;
}
